import { enterStudio } from './browser-test-helpers.mjs';
import { launchBrowser } from './browser-test-helpers.mjs';
import { mkdir,writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await launchBrowser();
await mkdir('visual-checks/exterior',{recursive:true});
try {
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:5189/?quality=high',{waitUntil:'networkidle'});
 await enterStudio(page);
 await enterStudio(page);
 await page.evaluate(()=>{const a=window.__OCTOBERLINE_211__;a.room.configure({weather:'autumn-wind',unease:'off'});a.setView('front',0);});
 await page.waitForTimeout(2500);
 await page.screenshot({path:'visual-checks/exterior/front.png'});
 await page.screenshot({path:'visual-checks/exterior/window.png',clip:{x:370,y:155,width:900,height:460}});
 const state=await page.evaluate(()=>{const a=window.__OCTOBERLINE_211__,l=a.room.livingCity;return {landmarks:l.landmarks.architecture,ciraTime:l.landmarks.animationTime,peco:a.room.getState().pecoCrown,leaf:Array.from(l.leaves.instanceMatrix.array),trees:l.trees.map(t=>t.tree.rotation.z),errors:[]};});
 await page.waitForTimeout(3500);
 await page.screenshot({path:'visual-checks/exterior/window-motion.png',clip:{x:370,y:155,width:900,height:460}});
 const moving=await page.evaluate(()=>{const r=window.__OCTOBERLINE_211__.room,l=r.livingCity;return {ciraTime:l.landmarks.animationTime,leaf:Array.from(l.leaves.instanceMatrix.array),trees:l.trees.map(t=>t.tree.rotation.z)};});
 assert(moving.ciraTime>state.ciraTime,'Cira shader clock must advance');
 assert.notDeepEqual(moving.leaf,state.leaf,'falling leaves must actually move');
 assert.notDeepEqual(moving.trees,state.trees,'tree branches must actually move');
 delete state.leaf;delete state.trees;state.motion={cira:true,fallingLeaves:true,trees:true};
 await page.waitForFunction(()=>window.__OCTOBERLINE_211__.room.getState().pecoCrown.scrollOffset>0,null,{timeout:20000});
 state.peco=await page.evaluate(()=>window.__OCTOBERLINE_211__.room.getState().pecoCrown);
 await page.evaluate(()=>{const r=window.__OCTOBERLINE_211__.room;r.setReducedMotion(true);r.livingCity.landmarks.update(0);});
 await page.waitForTimeout(300);
 await page.screenshot({path:'visual-checks/exterior/cira-0.png',clip:{x:370,y:155,width:900,height:460}});
 await page.evaluate(()=>window.__OCTOBERLINE_211__.room.livingCity.landmarks.update(18));
 await page.waitForTimeout(300);
 await page.screenshot({path:'visual-checks/exterior/cira-18.png',clip:{x:370,y:155,width:900,height:460}});
 await page.evaluate(()=>window.__OCTOBERLINE_211__.room.setWeatherPreset('snow',{immediate:true}));
 await page.waitForTimeout(400);
 await page.screenshot({path:'visual-checks/exterior/snow.png',clip:{x:370,y:155,width:900,height:460}});
 state.snow=await page.evaluate(()=>{const l=window.__OCTOBERLINE_211__.room.livingCity;return {houses:l.streetscape.snowAmount,landmarks:l.landmarks.snowCaps.material.opacity};});
 assert(state.snow.houses>0 && state.snow.landmarks>0,'new roofs must respond to snow');
 state.errors=errors;console.log(JSON.stringify(state,null,2));await writeFile('visual-checks/exterior/review.json',JSON.stringify(state,null,2));
 if(errors.length)throw new Error(errors.join('\n'));
}finally{await browser.close();}
